#pragma once
#include <iostream>
#include <vector>
#include <string>
#define _USE_MATH_DEFINES
#include <cmath>
#include <chrono>
#include <iomanip>
#include <fstream>
#include <cassert>
#include <exception>
#include <algorithm>
#include <limits>
#include <sstream>
#include <list>
#include <deque>
#include <stack>
#include <ctime>
#include <array>
#include <set>
#include <map>
#include <filesystem>
#include <queue>
#include <unordered_set>
#include <unordered_map>
#include <random>
#include <utility>
#include <optional>
