" VIM Configuration File
" Description: Optimized for C/C++ development, but useful also for other things.
" Author: Gerhard Gappmeier, edited by Blake Baird
"

" set UTF-8 encoding
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8
" disable vi compatibility (emulation of old bugs)
set nocompatible
" use indentation of previous line
set autoindent
set smartindent
set guifont=Consolas:h11:cANSI:qDRAFT
set autochdir
set noerrorbells visualbell
" use intelligent indentation for C
" configure tabwidth and insert spaces instead of tabs
set tabstop=2        " tab width is 4 spaces
set shiftwidth=2     " indent also with 4 spaces
set bs=2
set expandtab        " expand tabs to spaces
set wildmenu
set hlsearch
" install fzf
set rtp+=$VIM\fzf
"switch semicolon for colon
nmap ; ;
"switch semicolon for colon, even in visual mode
" https://vim.fandom.com/wiki/Map_semicolon_to_colon
map ; :
filetype plugin indent on
" wrap lines at 120 chars. 80 is somewaht antiquated with nowadays displays.
set textwidth=120
" turn syntax highlighting on
set t_Co=256
syntax on
colorscheme darkblue 
" turn relative line numbers on
set relativenumber
" highlight matching braces
set showmatch
" intelligent comments
set comments=sl:/*,mb:\ *,elx:\ */

" Install OmniCppComplete like described on http://vim.wikia.com/wiki/C++_code_completion
" This offers intelligent C++ completion when typing ‘.’ ‘->’ or <C-o>
" Load standard tag files
set tags+=~/.vim/tags/cpp
set tags+=~/.vim/tags/gl
set tags+=~/.vim/tags/sdl
set tags+=~/.vim/tags/qt4

" Install DoxygenToolkit from http://www.vim.org/scripts/script.php?script_id=987
let g:DoxygenToolkit_authorName="John Doe <john@doe.com>"

" Enhanced keyboard mappings
"
" in normal mode F2 will save the file
nmap <F2> :w<CR>
" in insert mode F2 will exit insert, save, enters insert again
imap <F2> <ESC>:w<CR>i
" edit vimrc file
map <F3> :e $VIM\vimrc<CR>
" switch between header/source with F4
map <F4> :e %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>
" recreate tags file with F5
map <F5> :!ctags -R –c++-kinds=+p –fields=+iaS –extra=+q . c:\SFML<CR>
" create doxygen comment
map <F6> :Dox<CR>
" build project using compile script
map <F8> :source %:p:h\compile.vim<CR> 
map <F9> :!..\build\game.exe<CR> 
map <F10> :term clang++ % -o %.exe<CR>
map <F11> :!%.exe<CR>
" goto definition with F12
map <F12> <C-]>
" in diff mode we use the spell check keys for merging

" MAPPINGS
"
if &diff
  ” diff settings
  map <M-Down> ]c
  map <M-Up> [c
  map <M-Left> do
  map <M-Right> dp
  map <F9> :new<CR>:read !svn diff<CR>:set syntax=diff buftype=nofile<CR>gg
else
  " spell settings
  :setlocal spell spelllang=en
  " set the spellfile - folders must exist
  set spellfile=~/.vim/spellfile.add
  map <M-Down> ]s
  map <M-Up> [s
endif

set nospell


